Issue/317 add web UI section to the configuration file iso5
inmanta/inmanta-ui pull request #330
Opened 2022-11-04 10:10 UTC by Hugo-Inmanta

# Description
- Move ui related options from inmanta-core to inmanta-ui
- Log a deprecation warning when the web-console or the dashboard sections are used 

closes #317 

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [ ] Attached issue to pull request
- [ ] Changelog entry
- [ ] Type annotations are present
- [ ] Code is clear and sufficiently documented
- [ ] No (preventable) type errors
- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )

# Reviewer Checklist:

- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Code is clear and sufficiently documented
- [ ] Correct, in line with design

2022-11-04 15:40 UTC, Hugo-Inmanta commented
Tests on jenkins are expected to fail until https://github.com/inmanta/inmanta-core/pull/5077 has been merged in

2022-11-07 13:40 UTC, arnaudsjs requested changes

2022-11-07 13:40 UTC, arnaudsjs commented on changelogs/unreleased/317-add-web-ui-section-to-the-configuration-file-iso5.yml
> +description: The 'dashboard' and 'web-console' sections are being deprecated. The 'web-ui' section should now be used instead for configuration options related to web interfaces.
```suggestion
description: The 'web-console' section is being deprecated. The 'web-ui' section should now be used instead for configuration options related to web interfaces.
```

2022-11-07 13:40 UTC, arnaudsjs commented on src/inmanta_ui/config.py
> +web_console_enabled = Option(
I like the banner above the dashboard-related configuration options. Let's also add one above the old and the new configuration options related to the web-console.

2022-11-07 13:40 UTC, arnaudsjs commented on changelogs/unreleased/317-add-web-ui-section-to-the-configuration-file-iso5.yml
> +destination-branches: [iso5]
This is an invalid PR. The base branch of this PR is `master`, but the changelog entry indicates that it should be merged into `iso5` only.

2022-11-07 13:40 UTC, arnaudsjs commented on tests/test_web_ui_options.py
> +from inmanta_ui import config as cfg
`opt` and `cfg` are chosen very arbitrarily. I would rename then to make it clear what they refer to:
```suggestion
from inmanta.server import config as opt_core
from inmanta_ui import config as opt_ui
```

2022-11-10 10:47 UTC, Hugo-Inmanta commented
This PR was based off the wrong branch.
New valid PR is here: https://github.com/inmanta/inmanta-ui/pull/336

2022-11-10 10:47 UTC, closed without merging