Issue/317 deprecate dashboard and web console section
inmanta/inmanta-ui pull request #336
Opened 2022-11-10 10:46 UTC by Hugo-Inmanta

# Description

- Move ui related options from inmanta-core to inmanta-ui
- Log a deprecation warning when the web-console or the dashboard sections are used 

part of #317 

closes *Add ticket reference here*

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [ ] Attached issue to pull request
- [ ] Changelog entry
- [ ] Type annotations are present
- [ ] Code is clear and sufficiently documented
- [ ] No (preventable) type errors
- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )

# Reviewer Checklist:

- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Code is clear and sufficiently documented
- [ ] Correct, in line with design

2022-11-14 07:49 UTC, arnaudsjs requested changes

2022-11-14 07:49 UTC, arnaudsjs commented on src/inmanta_ui/config.py
> +    predecessor_option=dash_client_id,
I don't think this is necessary actually. The dashboard will be removed in ISO6, so it doesn't make much sense to migrate the options to a different section. Do you agree?

2022-11-14 07:50 UTC, arnaudsjs commented on src/inmanta_ui/config.py
> +    predecessor_option=dash_client_id,
You can ignore this comment. We have to migrate the authentication-related option. So then it makes sense to migrate the other options as well.

2022-11-15 13:11 UTC, Hugo-Inmanta commented on src/inmanta_ui/config.py
> +    "[DEPRECATED USE :inmanta.config:option:`web-ui.console_enabled`] " "Whether the server should host the web-console or not",
I'm not sure I have check how those are rendering.
Checking right now

2022-11-15 13:41 UTC, Hugo-Inmanta commented on src/inmanta_ui/config.py
> +    "[DEPRECATED USE :inmanta.config:option:`web-ui.console_enabled`] " "Whether the server should host the web-console or not",
a4353c9e0745aabc23f8fc8d2ab199c7191af798 makes sure it's rendered properly

2022-11-16 07:11 UTC, arnaudsjs approved these changes

2022-11-16 13:48 UTC, inmantaci commented
Merged into branches iso5 in a4791012f97e14e4aefaab4aaa8fe52aaa1902d9

2022-11-16 13:48 UTC, closed without merging